name: 'slack-notification-action'
description: 'Github action to send notifications to slack'
author: amansson
inputs:
  payload:
    description: payload incoming slack webhook
outputs:
  time: # output will be available to future steps 
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
