name: "slack notification"
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: amansson/slack-notification-action@master
        with:
          payload: |
            {
              "text": "Pull Request form Github",
              "attachments": [
                {
                  "title": "${{ job.status }}: ${{ github.workflow }}",
                  "title_link": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
