name: "slack notification"
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: amansson/slack-notification-action@master
        with:
          payload: |
            {
              "text": "Pull Request form Github",
              "attachments": [
                {
                  "title": "${{ github.event.pull_request.title }},
                  "title_link": "${{ github.event.pull_request.url }}",
                  "text": "${{ github.event.pull_request.body }}",
                  "footer": "${{ github.event.pull_request.user.login }} at ${{ github.event.pull_request.created_at }}",
                  "color": "warning"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
