name: "slack notification"
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: amansson/slack-notification-action@master
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.pull_request.title }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":fox_face: Repo: ${{ github.event.pull_request.head.repo.full_name }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Type:*\nPULL REQUEST"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Reviewers:*\n${{ github.event.pull_request.requested_reviewers.forEach(element => return element.login) }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text":
                  {
                    "type": "mrkdwn",
                    "text": ${{ toJson(github.event.pull_request.body) }}
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|Link to pull request>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}